server:
  servlet:
    context-path: /hongtaiyang-admin
spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: api-tool
  main:
    allow-bean-definition-overriding: true
swagger2:
  apiInfo:
    title: 宏泰洋平台-后台管理系统api
    version: 1.0
    description: 宏泰洋平台-后台管理系统api
    contact:
      name: tangtuo
      url: http://127.0.0.1
      email: xxx
  apis:
    basePackage: com.hongtaiyang.admin

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hongtaiyang.common.entity




