server:
  servlet:
    context-path: /hongtaiyang-admin
spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: api-tool
  main:
    allow-bean-definition-overriding: true
  encrypt:
    rsaPublicKey: MIICCgKCAgEAwAuTz1JaJM6ZBpRgNcyYfhIfBVs+PQWslA25onuf9p2HKYNpsRoBUgdhWobQFPgoSQVN3MZnQdvCnfzaSNWYUWBsXZ2hnMZlJqwGLETuYLJ7da4EzToXasEAPGDHXwlNznMSIOqthGINr7QNmd7q8LlPIqvg49O3CY3Js/eSiZuxTosOW0RSvZ3W8oXsdr1s4eCkVxVPP5Kf/XBKk45JAveC53YnoRjQ49rkvN4xUh2sIJuoyleaCHFnCBE0nUFv+bNZipfGDnlDToI6ZXSniCm6YJ+JrjF1p9hp6OJRAx9R/8R6G2Q7IK8HD9tvVwvQFq8GMTPzj2A7J74mKp/uHdmL/u4uaf95jtmUHK0ecs+gaNkqb3GpEVO15JMvvoLqS8GHM+YHveCCpprbQP/PYY/gKVZzg0fcNAPWcDwJCUB+fJp8jt2oJGnRuF8hjFdN9ibWIHIdHAG337MCB5suvAaJKY08kEIoAeIxkXAiLgsfI3lATieWQEXm14smrtsutFtcuZCYEt7Fkh+2ITOd1NrZFl6UogwRTWmd3+gx6JaONojOFUQ3oUK+MBetzj/MMXgwE7y+RbfWGJJoSPjWTVvONC04eBSs0up7IdoFTwxy+feaGDbiRSHtQ2Keu1DSwLcr+ZORAPColCeaR2sGLWeCuPytIcS/kNDpgI/4UMECAwEAAQ==
    rsaPrivateKey: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAN0+tIO88stHnDMZn8ZlH3CcEiJw2JDBNizST1pkVHbLmnEcZpbm6qKuG0/Ey7rxHnMUq+bF/HkR68H7OVPoUOey3l3hjb1W1le3cia85A7RNE7XgmHmE/hXTeVev+5Q8Tr7s3fuvQMC6s2u9yvFsWOMQ7/kn4KMQGX6IueNRqmxAgMBAAECgYB1MZD3M3A8w5r26nza35fu0407lyDwVJg419JW5ExlfOY7QjsJdhoVwDoRYAI27SAe/3UrUfaxvw9t+oBcdPPdO5miTuXuepHM6b6K3N3ipdzCMXhH7WE+P98WJpqquEx3kB2epj0U0nSg1APk9xu0cEHs9EEwjeLIl0WYXIt4AQJBAPDRpkgGicGclDe+I/pzcqLHVmmgDgL65LgO3/VtEgOn2HUG+rEEBhwq1SNeR8AvAfE5iGbeEYNxk5+U1j+M4jECQQDrMStQV+3iZ0J+37bHXESTfOfsfZOceQMYZ2zJgEbU76eto29uFeHGTKvLvcFRYP5elv3BmTOCgQig4A7iQN+BAkEAzvvTSOrdslyrhHHYKKbb7A8bNbQM9wDAX3bhhefWaO/1+zghds43ljQ2d6zMTOHacIR7uba7JNgVAz+BGqQzsQJBAMeTBao7swT3kpmOxM8PILH2v+cR+HxCw7mlqc6jJ3fxlVvm39uOffODhBRzhOPFZpRllBcAJZGMZQH+nyKm4gECQGc0pqWREhnibbXx9cxMkO1JibZak0ziRAUUdu71DhCnPqNODLNFIJ8+I9lRiHfrLPTLbcG0l9y6G0rSGFGZ4ME=
swagger2:
  apiInfo:
    title: 宏泰洋平台-后台管理系统api
    version: 1.0
    description: 宏泰洋平台-后台管理系统api
    contact:
      name: tangtuo
      url: http://127.0.0.1
      email: xxx
  apis:
    basePackage: com.hongtaiyang.admin

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hongtaiyang.common.entity




