server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tang?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: 636392
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat ,wall
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      useGlobalDataSourceStat: true


  redis:
    database: 0
    host: localhost
    jedis:
      pool:
        max-active: 200
        max-idle: 10
        max-wait: -1ms
        min-idle: 0
    password: 123456
    port: 6379
    timeout: 5000ms


