server:
  servlet:
    context-path: /hongtaiyang-client
spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: api-tool
  main:
    allow-bean-definition-overriding: true
swagger2:
  apiInfo:
    title: 鸿泰洋平台-客户端api
    version: 1.0
    description: 鸿泰洋平台-客户端api
    contact:
      name: tangtuo
      url: http://127.0.0.1
      email: xxx
  apis:
    basePackage: com.hongtaiyang.client

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: cn.com.citydo.api.tool.interfaces.entity




