server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tangtuo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver


  redis:
    database: 0
    host: localhost
    jedis:
      pool:
        max-active: 200
        max-idle: 10
        max-wait: -1ms
        min-idle: 0
    password: 123456
    port: 6379
    timeout: 5000ms


